# #Question  printing the table of inputted number(3 different print statements)
# a=int(input("Enter a number: "))
# for i in range(1,11):
#     print(a,"X",i,"=",a*i)     #naive approach
    
# # for i in range(1,11):
# #     print("%d X %d="%(a,i), a*i)     #use of format specifiers

# # for i in range(1,11):
# #     print(f"{a}X{i}={a*i}")   #use of f strings 


# #Question   greeting specific persons(jinka naam "s" se start ho) in list
# l1=["harry","sohan","sachin","rahul"]
# for name in l1:
#     if name.startswith("s"):
#         print("hello",name)


# #Question   reattempting above question using while loop
# i=0
# while i<len(l1):
#     if l1[i].startswith("s"):
#         print("hello",l1[i])
#     i=i+1


# #Question   detecting whether given number is prime or not
# prime=1
# a=int(input("Enter the number: "))
# for i in range(2,a):
#     if(a%i==0):
#         prime=0
#         break
# if(prime==1):
#     print(a,"is prime")
# else:
#     print(a,"is not prime")


# #Question  finding sum of first n natural number using while loop
# a=int(input("Enter the number: "))
# sum=0
# for i in range(1,a+1):
#     sum=sum+i

# print(f"The sum of first {a} natural numbers is {sum}")


# #Question  finding factorial of a number using loops
# a=int(input("Enter the number: "))
# fac=1
# for i in range(2,a+1):
#     fac=fac*i
# print(f"The factorial of {a} is {fac}")


# #Question  printing normal star patter *,***,****** for n=3
# n=3
# for i in range(n):
#     print("*"*(2*i+1))


# #Question  printing centric star pattern of *,***,***** for n=3
# n=3 
# for i in range(n):
#     print(" "*(n-i-1),end=" ")   #this syntax kills the new line to be generated by print
#     print("*"*(2*i+1),end=" ")
#     print(" "*(n-i-1))

#Question printing multiplication table in reverse order
a=int(input("Enter the number: "))
for i in range(10,0,-1):
    print(f"{a} X {i} ={a*i}")